<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<?=$this->getChildHtml('head')?>
</head>
<body class="<?=$this->getBodyClass()?>">
	<?=$this->getChildHtml('after_body_start')?>
	<?=$this->getChildHtml('chromeframe')?>
	<?=$this->getChildHtml('global_notices')?>

	<?=$this->getChildHtml('header')?>
	<?=$this->getChildHtml('nav')?>

	<div role="main">
		<div class="centre-container">
			<div class="main-content with-one-sidebar">
				<?=$this->getChildHtml('breadcrumbs')?>
				<?=$this->getChildHtml('content')?>
			</div>
			<aside class="main-sidebar">
				<?=$this->getChildHtml('right')?>
			</aside>
		</div>
	</div>

	<?=$this->getChildHtml('footer')?>

	<?=$this->getChildHtml('before_body_end')?>
</body>
</html>