<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?=$this->getLang()?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="<?=$this->getLang()?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="<?=$this->getLang()?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?=$this->getLang()?>"> <!--<![endif]-->
<head>
	<?=$this->getChildHtml('head')?>
</head>
<body class="page-print <?=$this->getBodyClass()?>">
	<header class="print-head">
		<img src="<?=$this->getPrintLogoUrl() ?: $this->getSkinUrl('images/logo_print.gif')?>" class="logo" alt="">
		<?php if ($this->getPrintLogoText()): ?>
			<address>
				<?=nl2br($this->htmlEscape($this->getPrintLogoText()))?>
			</address>
		<?php endif ?>
	</header>

	<?=$this->getChildHtml('content')?>

	<div class="buttons-set">
		<button type="button" title="<?=$this->__('Close Window')?>" class="button" onclick="window.close();"><span><span><?=$this->__('Close Window')?></span></span></button>
	</div>

	<?=$this->getAbsoluteFooter()?>
</body>
</html>