<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */
?>
<?php if ($crumbs and is_array($crumbs)): ?>
	<div class="breadcrumbs">
		<ul class="breadcrumb">
			<?php foreach ($crumbs as $crumbName=>$crumbInfo): ?>
				<li class="<?=$crumbName?>">
					<?php

					// If there is a link associated with the item
					if ($crumbInfo['link']): ?>
						<a href="<?=$crumbInfo['link']?>" title="<?=$this->htmlEscape($crumbInfo['title'])?>">
							<?=$this->htmlEscape($crumbInfo['label'])?>
						</a>
					<?php

					// If there's no link associated
					else: ?>
						<?php echo $this->htmlEscape($crumbInfo['label']) ?>
					<?php endif ?>

					<?php

					// Add dividers for every link that's not the last one
					if( ! $crumbInfo['last']): ?>
						<span class="divider">/</span>
					<?php endif ?>
				</li>
			<?php endforeach ?>
		</ul>
	</div>
<?php endif ?>