<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */
?>
<!--[if lt IE 7]>
	<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->