<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */
?>
<footer role="contentinfo">
	<div class="container">
		<div class="row">
			<div class="span6">
				<?=$this->getChildHtml()?>
			</div>
			<div class="span6">
				<div class="pull-right">
					<?=$this->getCopyright()?>
				</div>
			</div>
		</div>
	</div>
</footer>