<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */
?>
<header role="banner">
	<div class="centre-container">

		<div class="logo-column">
			<h1 id="logo">
				<strong><?=$this->getLogoAlt()?></strong>
				<a href="<?=$this->getUrl('')?>" title="<?=$this->getLogoAlt()?>" class="logo">
					<img src="<?=$this->getLogoSrc()?>" alt="<?=$this->getLogoAlt()?>">
				</a>
			</h1>
		</div>

		<div class="quick-access">

			<?=$this->getChildHtml('topSearch')?>

			<p class="welcome-msg">
				<?=$this->getWelcome()?>
				<?=$this->getAdditionalHtml()?>
			</p>

			<?=$this->getChildHtml('topLinks')?>
			<?=$this->getChildHtml('store_language')?>

		</div>

	</div>
</header>