<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */
?>
<header role="banner">
	<div class="container">
		<div class="row">
			<div class="span3">
				<h1 id="logo">
					<strong><?=$this->getLogoAlt()?></strong>
					<a href="<?=$this->getUrl('')?>" title="<?=$this->getLogoAlt()?>" class="logo">
						<img src="<?=$this->getLogoSrc()?>" alt="<?=$this->getLogoAlt()?>">
					</a>
				</h1>
			</div>
			<div class="span6 offset3">
				<div class="quick-access">

					<?=$this->getChildHtml('topSearch')?>

					<p class="welcome-msg">
						<?=$this->getWelcome()?>
						<?=$this->getAdditionalHtml()?>
					</p>

					<?=$this->getChildHtml('topLinks')?>
					<?=$this->getChildHtml('store_language')?>

				</div>
			</div>
		</div>
	</div>
</header>