<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 - 2013 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Category navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
$categories = $this->getActiveStoreCategories();
$pages      = $this->getActiveStoreCmsPages();
$limit      = $this->getLimit();
$storeName  =  Mage::getStoreConfig('general/store_information/name');
?>
<?php if ($categories or $pages): ?>

	<nav role="navigation">
		<div class="container">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">

						<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</a>

						<?php if ($storeName): ?>
							<span class="hidden-desktop">
								<a class="brand" href="#"><?=$storeName?></a>
							</span>
						<?php endif ?>

						<div class="nav-collapse collapse">
							<ul class="nav">
								<?php

								// If categories are going first
								if ($this->getOrder() === 'categories'): ?>
									<?php if ($this->shouldDisplayCategories()): ?>
										<?php foreach ($categories as $category): ?>
											<?=$this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top/category.phtml')->setTopCategory($category)->setLimit($limit)->toHtml()?>
										<?php endforeach ?>
									<?php endif ?>
									<?php if ($this->shouldDisplayCmsPages()): ?>
										<?php foreach ($this->getActiveStoreCmsPages() as $page): ?>
											<?=$this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top/page.phtml')->setTopPage($page)->setLimit($limit)->toHtml()?>
										<?php endforeach ?>
									<?php endif ?>
								<?php

								// If CMS pages are going first
								else: ?>
									<?php if ($this->shouldDisplayCmsPages()): ?>
										<?php foreach ($this->getActiveStoreCmsPages() as $page): ?>
											<?=$this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top/page.phtml')->setTopPage($page)->setLimit($limit)->toHtml()?>
										<?php endforeach ?>
									<?php endif ?>
									<?php if ($this->shouldDisplayCategories()): ?>
										<?php foreach ($categories as $category): ?>
											<?=$this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top/category.phtml')->setTopCategory($category)->setLimit($limit)->toHtml()?>
										<?php endforeach ?>
									<?php endif ?>
								<?php endif ?>
							</ul>
						</div>

					</div>
				</div>
			</div>
		</div>
	</nav>

<?php endif ?>
