<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */

// Get resources
$item             = $this->getItem();
$isVisibleProduct = $item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp     = Mage::helper('catalog')->canApplyMsrp($item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<tr>
	<td class="a-center">
		<?php if ($this->hasProductUrl()): ?><a href="<?=$this->getProductUrl()?>" title="<?=$this->htmlEscape($this->getProductName())?>" class="product-image"><?php endif ?>

			<img src="<?=$this->getProductThumbnail()->resize(75) ?>" alt="<?=$this->htmlEscape($this->getProductName())?>" class="img-polaroid img-rounded">

		<?php if ($this->hasProductUrl()): ?></a><?php endif ?>
	</td>
	<td>
		<h2 class="product-name">
		<?php if ($this->hasProductUrl()): ?>
			<a href="<?=$this->getProductUrl()?>"><?=$this->htmlEscape($this->getProductName())?></a>
		<?php else: ?>
			<?=$this->htmlEscape($this->getProductName())?>
		<?php endif ?>
		</h2>
		<?php if ($options = $this->getOptionList()): ?>
		<dl class="item-options">
			<?php foreach ($options as $option) : ?>
			<?php $formatedOptionValue = $this->getFormatedOptionValue($option)?>
			<dt><?=$this->htmlEscape($option['label'])?></dt>
			<dd<?php if (isset($formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?=$formatedOptionValue['value']?>
				<?php if (isset($formatedOptionValue['full_view'])): ?>
				<div class="truncated_full_value">
					<dl class="item-options">
						<dt><?=$this->htmlEscape($option['label'])?></dt>
						<dd><?=$formatedOptionValue['full_view']?></dd>
					</dl>
				</div>
				<?php endif ?>
			</dd>
			<?php endforeach ?>
		</dl>
		<?php endif ?>
		<?php if ($messages = $this->getMessages()): ?>
		<?php foreach ($messages as $message): ?>
			<p class="item-msg <?=$message['type']?>">* <?=$this->escapeHtml($message['text'])?></p>
		<?php endforeach ?>
		<?php endif ?>
		<?php $addInfoBlock = $this->getProductAdditionalInformationBlock() ?>
		<?php if ($addInfoBlock): ?>
			<?=$addInfoBlock->setItem($item)->toHtml()?>
		<?php endif ?>
	</td>
	<td class="a-center">
		<?php if ($isVisibleProduct): ?>
		<a href="<?=$this->getConfigureUrl()?>" title="<?=$this->__('Edit item parameters')?>"><?=$this->__('Edit')?></a>
		<?php endif?>
	</td>
	<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
	<td class="a-center">
		<?php if ($isVisibleProduct): ?>
			<a href="<?=$this->helper('wishlist')->getMoveFromCartUrl($item->getId()) ?>" class="link-wishlist use-ajax"><?=$this->__('Move') ?></a>
		<?php endif?>
	</td>
	<?php endif?>

	<?php if ($canApplyMsrp): ?>
		<td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif ?>>
			<span class="cart-price">
				<span class="cart-msrp-unit"><?=$this->__('See price before order confirmation.') ?></span>
				<?php $helpLinkId = 'cart-msrp-help-' . $item->getId() ?>
				<a id="<?=$helpLinkId?>" href="#" class="map-help-link"><?=$this->__("What's this?") ?></a>
				<script type="text/javascript">
					Catalog.Map.addHelpLink($('<?=$helpLinkId?>'), "<?=$this->__("What's this?")?>");
				</script>
			</span>
		</td>
	<?php else: ?>

		<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td class="a-right">
			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<span class="cart-price">
			<?php endif ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?=$this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()) ?>
				<?php else: ?>
					<?=$this->helper('checkout')->formatPrice($item->getCalculationPrice())?>
				<?php endif ?>

			</span>


			<?php if (Mage::helper('weee')->getApplied($item)): ?>

				<div class="cart-tax-info" id="eunit-item-tax-details<?=$item->getId() ?>" style="display:none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount'],true,true) ?></span>
						<?php endforeach ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true) ?></span>
						<?php endforeach ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true) ?></span>
						<?php endforeach ?>
					<?php endif ?>
				</div>

				<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
						<span class="weee"><?=Mage::helper('weee')->__('Total') ?>: <?=$this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()) ?></span>
					</div>
				<?php endif ?>
			<?php endif ?>
		</td>
		<?php endif ?>
		<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<td>
			<?php $incl = $this->helper('checkout')->getPriceInclTax($item) ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<span class="cart-price">
			<?php endif ?>

				<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?=$this->helper('checkout')->formatPrice($incl+$item->getWeeeTaxAppliedAmount()) ?>
				<?php else: ?>
					<?=$this->helper('checkout')->formatPrice($incl-$item->getWeeeTaxDisposition())?>
				<?php endif ?>

			</span>
			<?php if (Mage::helper('weee')->getApplied($item)): ?>

				<div class="cart-tax-info" id="unit-item-tax-details<?=$item->getId() ?>" style="display:none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount'],true,true) ?></span>
						<?php endforeach ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true) ?></span>
						<?php endforeach ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
							<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true) ?></span>
						<?php endforeach ?>
					<?php endif ?>
				</div>

				<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
						<span class="weee"><?=Mage::helper('weee')->__('Total incl. tax') ?>: <?=$this->helper('checkout')->formatPrice($incl+$item->getWeeeTaxAppliedAmount()) ?></span>
					</div>
				<?php endif ?>
			<?php endif ?>
		</td>
		<?php endif ?>
	<?php endif ?>
	<td class="a-center">
		<input type="number" name="cart[<?=$item->getId()?>][qty]" value="<?=$this->getQty()?>" size="4" title="<?=$this->__('Qty')?>" class="input-text input-mini qty" maxlength="12" min="0">
	</td>
	<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$item->getNoSubtotal()): ?>
	<td class="a-right">
		<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
		<?php else: ?>
			<span class="cart-price">
		<?php endif ?>

			<?php if ($canApplyMsrp): ?>
				<span class="cart-msrp-subtotal">--</span>
			<?php else: ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?=$this->helper('checkout')->formatPrice($item->getRowTotal()+$item->getWeeeTaxAppliedRowAmount()+$item->getWeeeTaxRowDisposition()) ?>
				<?php else: ?>
					<?=$this->helper('checkout')->formatPrice($item->getRowTotal())?>
				<?php endif ?>
			<?php endif ?>

		</span>
		<?php if (Mage::helper('weee')->getApplied($item)): ?>

			<div class="cart-tax-info" id="esubtotal-item-tax-details<?=$item->getId() ?>" style="display:none;">
				<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true) ?></span>
					<?php endforeach ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span>
					<?php endforeach ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span>
					<?php endforeach ?>
				<?php endif ?>
			</div>

			<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
					<span class="weee"><?=Mage::helper('weee')->__('Total') ?>: <?=$this->helper('checkout')->formatPrice($item->getRowTotal()+$item->getWeeeTaxAppliedRowAmount()+$item->getWeeeTaxRowDisposition()) ?></span>
				</div>
			<?php endif ?>
		<?php endif ?>
	</td>
	<?php endif ?>
	<?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$item->getNoSubtotal()): ?>
	<td>
		<?php $incl = $this->helper('checkout')->getSubtotalInclTax($item) ?>
		<?php if (Mage::helper('weee')->typeOfDisplay($item, array(1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
			<span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
		<?php else: ?>
			<span class="cart-price">
		<?php endif ?>

			<?php if ($canApplyMsrp): ?>
				<span class="cart-msrp-subtotal">--</span>
			<?php else: ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?=$this->helper('checkout')->formatPrice($incl+$item->getWeeeTaxAppliedRowAmount()) ?>
				<?php else: ?>
					<?=$this->helper('checkout')->formatPrice($incl-$item->getWeeeTaxRowDisposition())?>
				<?php endif ?>
			<?php endif ?>

		</span>


		<?php if (Mage::helper('weee')->getApplied($item)): ?>

			<div class="cart-tax-info" id="subtotal-item-tax-details<?=$item->getId() ?>" style="display:none;">
				<?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true) ?></span>
					<?php endforeach ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span>
					<?php endforeach ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
					<?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
						<span class="weee"><?=$tax['title'] ?>: <?=Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span>
					<?php endforeach ?>
				<?php endif ?>
			</div>

			<?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales') && $item->getWeeeTaxAppliedAmount()): ?>
				<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?=$item->getId() ?>', this, 'cart-tax-total-expanded');">
					<span class="weee"><?=Mage::helper('weee')->__('Total incl. tax') ?>: <?=$this->helper('checkout')->formatPrice($incl+$item->getWeeeTaxAppliedRowAmount()) ?></span>
				</div>
			<?php endif ?>
		<?php endif ?>
	</td>
	<?php endif ?>
	<td class="a-center"><a href="<?=$this->getDeleteUrl()?>" title="<?=$this->__('Remove item')?>" class="btn-remove">&times;</a></td>
</tr>
