<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */

$catalogSearchHelper = $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?=$catalogSearchHelper->getResultUrl()?>" method="get">
	<div class="form-search">
		<div class="input-append">
			<input id="search" type="text" name="<?=$catalogSearchHelper->getQueryParamName()?>" value="<?=$catalogSearchHelper->getEscapedQueryText()?>" class="input-text search-query" maxlength="<?=$catalogSearchHelper->getMaxQueryLength()?>">
			<button type="submit" title="<?=$this->__('Search')?>" class="btn">
				<span><span><?=$this->__('Search')?></span></span>
			</button>
		</div>
		<div id="search_autocomplete" class="search-autocomplete"></div>
		<script type="text/javascript">
		//<![CDATA[
			var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?=$this->__('Search entire store here...')?>');
			searchForm.initAutocomplete('<?=$catalogSearchHelper->getSuggestUrl()?>', 'search_autocomplete');
		//]]>
		</script>
	</div>
</form>