<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 - 2013 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */

$catalogSearchHelper = $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?=$catalogSearchHelper->getResultUrl()?>" method="get">
	<div class="clearfix">
		<div class="form-search pull-right">
			<div class="input-append">
				<input id="search" type="text" name="<?=$catalogSearchHelper->getQueryParamName()?>" value="<?=$catalogSearchHelper->getEscapedQueryText()?>" class="input-text search-query" maxlength="<?=$catalogSearchHelper->getMaxQueryLength()?>" placeholder="<?=$this->__('Search entire store here...')?>">
				<button type="submit" title="<?=$this->__('Search')?>" class="btn">
					<span><span><?=$this->__('Search')?></span></span>
				</button>
			</div>
			<div class="dropdown open">
				<div id="search_autocomplete" class="search-autocomplete dropdown-menu"></div>
			</div>
			<script type="text/javascript">
			//<![CDATA[
				var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
				searchForm.initAutocomplete('<?=$catalogSearchHelper->getSuggestUrl()?>', 'search_autocomplete');
			//]]>
			</script>
		</div>
	</div>
</form>
