<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
	<div class="page-title title-buttons">
		<h1><?=$this->__('Shopping Cart') ?></h1>
		<?php if ( ! $this->hasError()): ?>
		<ul class="checkout-types">
		<?php foreach ($this->getMethods('top_methods') as $method): ?>
			<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
			<li><?=$methodHtml?></li>
			<?php endif ?>
		<?php endforeach ?>
		</ul>
		<?php endif ?>
	</div>
	<?=$this->getMessagesBlock()->getGroupedHtml() ?>
	<?=$this->getChildHtml('form_before') ?>
	<form action="<?=$this->getUrl('checkout/cart/updatePost') ?>" method="post" class="cart-form">
		<table id="shopping-cart-table" class="table table-bordered table-striped cart-table">

				<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1) ?>
				<thead>
					<tr>
						<th rowspan="<?=$mergedCells?>">&nbsp;</th>
						<th rowspan="<?=$mergedCells?>"><span class="nobr"><?=$this->__('Product Name') ?></span></th>
						<th rowspan="<?=$mergedCells?>"></th>
						<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
						<th rowspan="<?=$mergedCells?>" class="a-center"><span class="nobr"><?=$this->__('Move to Wishlist') ?></span></th>
						<?php endif ?>
						<th class="a-center" colspan="<?=$mergedCells?>"><span class="nobr"><?=$this->__('Unit Price') ?></span></th>
						<th rowspan="<?=$mergedCells?>" class="a-center"><?=$this->__('Qty') ?></th>
						<th class="a-center" colspan="<?=$mergedCells?>"><?=$this->__('Subtotal') ?></th>
						<th rowspan="<?=$mergedCells?>" class="a-center">&nbsp;</th>
					</tr>
					<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<tr>
						<th class="a-right"><?=$this->helper('tax')->getIncExcTaxLabel(false) ?></th>
						<th><?=$this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						<th class="a-right"><?=$this->helper('tax')->getIncExcTaxLabel(false) ?></th>
						<th><?=$this->helper('tax')->getIncExcTaxLabel(true) ?></th>
					</tr>
					<?php endif ?>
				</thead>
				<tbody>
				<?php foreach($this->getItems() as $_item): ?>
					<?=$this->getItemHtml($_item) ?>
				<?php endforeach ?>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="50" class="a-right">
							<?php if ($this->getContinueShoppingUrl()): ?>
								<button type="button" title="<?=$this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?=$this->getContinueShoppingUrl() ?>')"><span><span><?=$this->__('Continue Shopping') ?></span></span></button>
							<?php endif ?>
							<button type="submit" name="update_cart_action" value="update_qty" title="<?=$this->__('Update Shopping Cart')?>" class="button btn-update"><span><span><?=$this->__('Update Shopping Cart')?></span></span></button>
							<button type="submit" name="update_cart_action" value="empty_cart" title="<?=$this->__('Clear Shopping Cart')?>" class="button btn-empty" id="empty_cart_button"><span><span><?=$this->__('Clear Shopping Cart')?></span></span></button>
							<!--[if lt IE 8]>
							<input type="hidden" id="update_cart_action_container">
							<script type="text/javascript">
							//<![CDATA[
								Event.observe(window, 'load', function()
								{
									// Internet Explorer (lt 8) does not support value attribute in button elements
									$emptyCartButton = $('empty_cart_button');
									$cartActionContainer = $('update_cart_action_container');
									if ($emptyCartButton && $cartActionContainer) {
										Event.observe($emptyCartButton, 'click', function()
										{
											$emptyCartButton.setAttribute('name', 'update_cart_action_temp');
											$cartActionContainer.setAttribute('name', 'update_cart_action');
											$cartActionContainer.setValue('empty_cart');
										});
									}

								});
							//]]>
							</script>
							<![endif]-->
						</td>
					</tr>
				</tfoot>
			</table>
	</form>
	<div class="cart-collaterals">
		<div class="row">
			<div class="span3">
				<div class="collateral-crossell">
					<?=$this->getChildHtml('crossell')?>
				</div>
			</div>
			<div class="span3">
				<?php if ( ! $this->getIsVirtual()): ?>
					<div class="collaterla-shipping">
						<?=$this->getChildHtml('shipping')?>
					</div>
				<?php endif ?>
			</div>
			<div class="span3">
				<div class="collateral-coupon">
					<?=$this->getChildHtml('coupon') ?>
				</div>
				<div class="collateral-misc">
					<?=$this->getChildHtml('checkout.cart.extra') ?>
				</div>
			</div>
			<div class="span3">
				<div class="collateral-totals">
					<div class="totals">
						<?=$this->getChildHtml('totals')?>
						<?php if ( ! $this->hasError()): ?>
						<ul class="checkout-types">
						<?php foreach ($this->getMethods('methods') as $method): ?>
							<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
							<li><?=$methodHtml?></li>
							<?php endif ?>
						<?php endforeach; ?>
						</ul>
						<?php endif ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
