<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

// Get resources
$category        = $this->getRecursionCategory();
$childCategories = $this->getActiveChildrenCategories($category);
$level           = $this->getLevel();
$limit           = $this->getLimit();
?>
<?php if ($category and $level): ?>
	<li class="level-<?=$level?>-item <?=(count($childCategories) > 0) ? 'dropdown-submenu' : null?>">
		<a href="<?=$this->getCategoryUrl($category)?>" class="level-<?=$level?>-link <?=$this->isCategoryActive($category) ? 'active' : null?>">
			<?=$category->getName()?>
		</a>

		<?php if (( ! $limit or $limit > $level) and count($childCategories) > 0): ?>
			<ul class="dropdown-menu level-<?=++$level?>">
				<?php foreach ($childCategories as $childCategory): ?>
					<?=$this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top/recursive.phtml')->setLevel($level)->setLimit($limit)->setRecursionCategory($childCategory)->toHtml()?>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
	</li>
<?php endif ?>