<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Chris Norton
 * @copyright  Copyright (c) 2009 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
$payment = $order->getPayment();
?>
<?php if($payment->getMethod() == 'bpay'): ?>
    <?php
    $bpay = Mage::getModel('australia/payment_bpay');
    $data = array(
        'biller_code' => $bpay->getBillerCode(),
        'ref' => $bpay->getRef()
    );
    $payment->setAdditionalData(serialize($data));
    $payment->save();
    
    $order->addStatusToHistory('pending_bpay', 'Order placed with BPAY', false);
    $order->save();
    ?>
    <?php echo Mage::helper('australia/bpay')->bpayInfoBlock($data['biller_code'], $data['ref']); ?>
<?php endif; ?>
