<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */

$description = $this->getProduct()->getDescription();
?>
<?php if ($description): ?>
	<h3><?=$this->__('Details')?></h3>
	<article class="std">
		<?=$this->helper('catalog/output')->productAttribute($this->getProduct(), $description, 'description')?>
	</article>
<?php endif ?>