<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */
$links = $this->getLinks();
$index = 1;
$count = count($links);
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="nav nav-pills nav-stacked">
            <?php foreach ($links as $link): ?>
                <li class="<?=($this->isActive($link)) ? 'active' : null?>">
                    <a href="<?=$link->getUrl()?>">
                        <?=$link->getLabel()?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
