<?php if ($this->shouldShowMap()): ?>
	<script>
	jQuery(document).ready(function($) {

		$(document).ready(function() {
            var mapDom = $('#enhancedcontacts-map');
            mapDom.css('height', '400px');
            mapDom.css('width', '100%');

            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({
            	address : '<?=$this->getAddress()?>'
            }, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    var latlng = results[0].geometry.location;
                    var map = new google.maps.Map(mapDom.get(0), {
                       zoom                     : 13,
                       center                   : latlng,
                       mapTypeId                : google.maps.MapTypeId.ROADMAP,
                       mapTypeControl           : true,
                       mapTypeControlOptions    :
                       {
                           style : google.maps.MapTypeControlStyle.DROPDOWN_MENU
                       },
                       navigationControl        : true,
                       navigationControlOptions : {
                           style : google.maps.NavigationControlStyle.SMALL
                       },
					   streetViewControl        : true
                    });

                    var marker = new google.maps.Marker(
                    {
                       map : map,
                       position : latlng
                    });
                }
            });
        });

	});
	</script>

	<div id="enhancedcontacts-map"></div>
<?php endif ?>