<div class="container">
    <footer role="contentinfo">
        <?php echo $this->getChildHtml() ?>
        <p class="bugs">
            <?php echo $this->__('Magento Boilerplate') ?> - <a href="http://www.webcomm.com.au/" target="_blank" title="eCommerce Websites Australia"><strong><?php echo $this->__('Another Webcomm Product') ?></strong></a> <?php echo $this->__('(Magento ver. %s)', Mage::getVersion()) ?>
        </p>
        <address><?php echo $this->getCopyright() ?></address>
    </footer>
</div>
