<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php if ($_menu): ?>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main">
                    <span class="sr-only"><?php echo $this->__('Toggle Navigation') ?></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse navbar-main">
                <ul class="nav navbar-nav">
                    <?php echo $_menu ?>
                </ul>
            </div>

        </nav>
    </div>
<?php endif ?>

