<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 - 2013 Webcomm Pty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if ($this->getCollection()->getSize()): ?>
<div class="toolbar">
	<div class="pager">

		<div class="amount-limiter">
			<p class="amount">
				<?php if ($this->getLastPageNum()>1): ?>
					<?=$this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum())?>
				<?php else: ?>
					<strong><?=$this->__('%s Item(s)', $this->getTotalNum())?></strong>
				<?php endif ?>
			</p>

			<div class="limiter form-inline">
				<label><?=$this->__('Show')?></label>
				<select onchange="setLocation(this.value)" class="input-mini">
					<?php foreach ($this->getAvailableLimit() as $key => $limit): ?>
						<option value="<?=$this->getLimitUrl($key)?>"<?php if ($this->isLimitCurrent($key)): ?> selected="selected"<?php endif ?>>
							<?=$limit?>
						</option>
					<?php endforeach ?>
				</select> <?=$this->__('per page')?>
			</div>
		</div>

		<?=$this->getPagerHtml()?>

	</div>

	<?php if ($this->isExpanded()): ?>
		<div class="sorter">
			<?php if ( $this->isEnabledViewSwitcher() ): ?>
			<p class="view-mode">
				<?php $modes = $this->getModes(); ?>
				<?php if ($modes && count($modes)>1): ?>
				<label><?=$this->__('View as')?>:</label>
				<?php foreach ($this->getModes() as $code => $label): ?>
					<?php if ($this->isModeActive($code)): ?>
						<strong title="<?=$label?>" class="<?=strtolower($code)?>"><?=$label?></strong>&nbsp;
					<?php else: ?>
						<a href="<?=$this->getModeUrl($code)?>" title="<?=$label?>" class="<?=strtolower($code)?>"><?=$label?></a>&nbsp;
					<?php endif ?>
				<?php endforeach ?>
				<?php endif ?>
			</p>
			<?php endif ?>

			<div class="sort-by form-inline">
				<label><?=$this->__('Sort By')?></label>
				<select onchange="setLocation(this.value)" class="input-small">
					<?php foreach ($this->getAvailableOrders() as $key => $order): ?>
						<option value="<?=$this->getOrderUrl($key, 'asc')?>"<?php if ($this->isOrderCurrent($key)): ?> selected="selected"<?php endif ?>>
							<?=$this->__($order)?>
						</option>
					<?php endforeach ?>
				</select>
				<?php if ($this->getCurrentDirection() == 'desc'): ?>
					<a href="<?=$this->getOrderUrl(null, 'asc')?>" title="<?=$this->__('Set Ascending Direction')?>"><img src="<?=$this->getSkinUrl('images/i_desc_arrow.gif')?>" alt="<?=$this->__('Set Ascending Direction')?>" class="v-middle"></a>
				<?php else: ?>
					<a href="<?=$this->getOrderUrl(null, 'desc')?>" title="<?=$this->__('Set Descending Direction')?>"><img src="<?=$this->getSkinUrl('images/i_asc_arrow.gif')?>" alt="<?=$this->__('Set Descending Direction')?>" class="v-middle"></a>
				<?php endif ?>
			</div>
		</div>
	<?php endif ?>
</div>
<?php endif ?>
