<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */

$productCollection = $this->getLoadedProductCollection();
$helper            = $this->helper('catalog/output');
?>
<?php if ( ! $productCollection->count()): ?>
	<p class="note-msg"><?=$this->__('There are no products matching the selection.')?></p>
<?php else: ?>
	<div class="category-products">
		<?=$this->getToolbarHtml()?>

		<?php

		// We're in list mode
		if ($this->getMode() != 'grid'): ?>
			<ol class="products-list" id="products-list">
				<?php foreach ($productCollection as $product): ?>
					<?php

					$productNameStripped = $this->stripTags($product->getName(), null, true);
					$compareUrl          = $this->getAddToCompareUrl($product);
					?>

					<li class="item">

						<a href="<?=$product->getProductUrl()?>" title="<?=$this->stripTags($this->getImageLabel($product, 'small_image'), null, true)?>" class="product-image">
							<img src="<?=$this->helper('catalog/image')->init($product, 'small_image')->resize(135)?>" alt="<?=$this->stripTags($this->getImageLabel($product, 'small_image'), null, true)?>">
						</a>

						<div class="product-shop">
							<div class="f-fix">

								<h2 class="product-name">
									<a href="<?=$product->getProductUrl()?>" title="<?=$productNameStripped?>"><?=$helper->productAttribute($product, $product->getName() , 'name')?></a>
								</h2>

								<?php if ($product->getRatingSummary()): ?>
									<?=$this->getReviewsSummaryHtml($product)?>
								<?php endif ?>

								<div class="clearfix">
									<?=$this->getPriceHtml($product, true)?>

									<?php if ($product->isSaleable()): ?>
										<p><button type="button" title="<?=$this->__('Add to Cart')?>" class="button btn-cart" onclick="setLocation('<?=$this->getAddToCartUrl($product)?>')"><span><span><?=$this->__('Add to Cart')?></span></span></button></p>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?=$this->__('Out of stock')?></span></p>
									<?php endif ?>
								</div>

								<article class="desc std">
									<?=$helper->productAttribute($product, $product->getShortDescription(), 'short_description')?>
									<a href="<?=$product->getProductUrl()?>" title="<?=$productNameStripped?>" class="link-learn"><?=$this->__('Learn More')?></a>
								</article>

								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()): ?>
										<li>
											<a href="<?=$this->helper('wishlist')->getAddUrl($product)?>" class="link-wishlist"><?=$this->__('Add to Wishlist')?></a>
										</li>
									<?php endif ?>
									<?php if ($compareUrl): ?>
										<li>
											<a href="<?=$compareUrl?>" class="link-compare"><?=$this->__('Add to Compare')?></a>
										</li>
									<?php endif ?>
								</ul>

							</div>
						</div>
					</li>

				<?php endforeach ?>
			</ol>

		<?php

		// We're in grid mode
		else: ?>

			<?php

			$collectionSize = $productCollection->count();
			$columnCount    = $this->getColumnCount();
			$i              = 0;
			?>
			<?php foreach ($productCollection as $product): ?>
				<?php

				$compareUrl = $this->getAddToCompareUrl($product);

				// Start new row
				if ($i++ % $columnCount == 0): ?>
					<ul class="products-grid">
				<?php endif ?>
					<li class="item-column">
						<div class="item">
							<a href="<?=$product->getProductUrl()?>" title="<?=$this->stripTags($this->getImageLabel($product, 'small_image'), null, true)?>" class="product-image">
								<img src="<?=$this->helper('catalog/image')->init($product, 'small_image')->resize(135)?>" alt="<?=$this->stripTags($this->getImageLabel($product, 'small_image'), null, true)?>">
							</a>

							<h2 class="product-name">
								<a href="<?=$product->getProductUrl()?>" title="<?=$this->stripTags($product->getName(), null, true)?>"><?=$helper->productAttribute($product, $product->getName(), 'name')?></a>
							</h2>

							<?php if ($product->getRatingSummary()): ?>
								<?=$this->getReviewsSummaryHtml($product, 'short')?>
							<?php endif ?>

							<?=$this->getPriceHtml($product, true)?>

							<div class="actions">

								<?php if ($product->isSaleable()): ?>
									<button type="button" title="<?=$this->__('Add to Cart')?>" class="button btn-cart" onclick="setLocation('<?=$this->getAddToCartUrl($product)?>')"><span><span><?=$this->__('Add to Cart')?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?=$this->__('Out of stock')?></span></p>
								<?php endif ?>

								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li>
											<a href="<?=$this->helper('wishlist')->getAddUrl($product)?>" class="link-wishlist"><?=$this->__('Add to Wishlist')?></a>
										</li>
									<?php endif ?>
									<?php if ($compareUrl): ?>
										<li>
											<a href="<?=$compareUrl?>" class="link-compare"><?=$this->__('Add to Compare')?></a>
										</li>
									<?php endif ?>
								</ul>

							</div>
						</div>
					</li>

				<?php

				// Close row
				if ($i % $columnCount == 0 or $i == $collectionSize): ?>
					</ul>
				<?php endif ?>
			<?php endforeach ?>
		<?php endif ?>

		<div class="toolbar-bottom">
			<?=$this->getToolbarHtml()?>
		</div>
	</div>
<?php endif ?>