<?php
/**
 * Webcomm Magento Boilerplate
 *
 * @copyright   Copyright (c) 2012 Webcomm Pyty Ltd
 * @link        http://webcomm.com.au
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */

$helper     = $this->helper('catalog/output');
$product    = $this->getProduct();
$additional = $this->getChildGroup('detailed_info', 'getChildHtml');
?>
<script>
	var optionsPrice = new Product.OptionsPrice(<?=$this->getJsonConfig()?>);
</script>
<div id="messages_product_view"><?=$this->getMessagesBlock()->getGroupedHtml()?></div>
<div class="product-view">
	<div class="product-essential">
		<form action="<?=$this->getSubmitUrl($product)?>" method="post" id="product_addtocart_form"<?php if ($product->getOptions()): ?> enctype="multipart/form-data"<?php endif ?>>
			<div class="no-display">
				<input type="hidden" name="product" value="<?=$product->getId()?>">
				<input type="hidden" name="related_product" id="related-products-field" value="">
			</div>

			<div class="product-shop">
				<div class="product-name">
					<h1><?=$helper->productAttribute($product, $product->getName(), 'name')?></h1>
				</div>

				<?php if ($this->canEmailToFriend()): ?>
					<p class="email-friend"><a href="<?=$this->helper('catalog/product')->getEmailToFriendUrl($product)?>"><?=$this->__('Email to a Friend')?></a></p>
				<?php endif ?>

				<?=$this->getReviewsSummaryHtml($product, false, true)?>
				<?=$this->getChildHtml('alert_urls')?>
				<?=$this->getChildHtml('product_type_data')?>
				<?=$this->getTierPriceHtml()?>
				<?=$this->getChildHtml('extrahint')?>

				<?php if ( ! $this->hasOptions()): ?>
					<div class="add-to-box">
						<?php if ($product->isSaleable()): ?>
							<?=$this->getChildHtml('addtocart')?>
							<?php if ( $this->helper('wishlist')->isAllow() or $compareUrl=$this->helper('catalog/product_compare')->getAddUrl($product)): ?>
								<span class="or"><?=$this->__('OR')?></span>
							<?php endif ?>
						<?php endif ?>
						<?=$this->getChildHtml('addto')?>
					</div>
					<?=$this->getChildHtml('extra_buttons')?>
				<?php elseif ( ! $product->isSaleable()): ?>
					<div class="add-to-box">
						<?=$this->getChildHtml('addto')?>
					</div>
				<?php endif ?>

				<?php if ($product->getShortDescription()): ?>
					<div class="short-description">
						<h2><?=$this->__('Quick Overview')?></h2>
						<article class="std"><?=$helper->productAttribute($product, nl2br($product->getShortDescription()), 'short_description')?></article>
					</div>
				<?php endif ?>

				<?=$this->getChildHtml('other');?>

				<?php if ($product->isSaleable() and $this->hasOptions()): ?>
					<?=$this->getChildChildHtml('container1', '', true, true)?>
				<?php endif ?>

			</div>

			<div class="product-img-box">
				<?=$this->getChildHtml('media')?>
			</div>

			<div class="clearer"></div>
			<?php if ($product->isSaleable() and $this->hasOptions()): ?>
				<?=$this->getChildChildHtml('container2', '', true, true)?>
			<?php endif ?>
		</form>
		<script>
		//<![CDATA[
			var productAddToCartForm = new VarienForm('product_addtocart_form');
			productAddToCartForm.submit = function(button, url) {
				if (this.validator.validate()) {
					var form = this.form;
					var oldUrl = form.action;

					if (url) {
					   form.action = url;
					}
					var e = null;
					try {
						this.form.submit();
					} catch (e) {
					}
					this.form.action = oldUrl;
					if (e) {
						throw e;
					}

					if (button && button != 'undefined') {
						button.disabled = true;
					}
				}
			}.bind(productAddToCartForm);

			productAddToCartForm.submitLight = function(button, url){
				if (this.validator) {
					var nv = Validation.methods;
					delete Validation.methods['required-entry'];
					delete Validation.methods['validate-one-required'];
					delete Validation.methods['validate-one-required-by-name'];
					// Remove custom datetime validators
					for (var methodName in Validation.methods) {
						if (methodName.match(/^validate-datetime-.*/i)) {
							delete Validation.methods[methodName];
						}
					}

					if (this.validator.validate()) {
						if (url) {
							this.form.action = url;
						}
						this.form.submit();
					}
					Object.extend(Validation.methods, nv);
				}
			}.bind(productAddToCartForm);
		//]]>
		</script>
	</div>

	<ul class="nav nav-tabs">
		<?php

		$i = 0;
		foreach ($additional as $alias => $html): ?>
			<li class="<?=$i++ === 0 ? 'active' : null?>">
				<a href="#product-collateral-<?=$this->escapeHtml($alias)?>" data-toggle="tab">
					<?=$this->escapeHtml(($this->getChildData($alias, 'title')) ?: $alias)?>
				</a>
			</li>
		<?php endforeach ?>
	</ul>
	<div class="tab-content">
		<?php

		$i = 0;
		foreach ($additional as $alias => $html): ?>
			<div class="tab-pane <?=$i++ === 0 ? 'active' : null?>" id="product-collateral-<?=$this->escapeHtml($alias)?>">
				<?=$html?>
			</div>
		<?php endforeach ?>
	</div>

<!-- 	<div class="product-collateral">
		<?=$this->getChildHtml('upsell_products')?>
		<?=$this->getChildHtml('product_additional_data')?>
	</div> -->
</div>
